# Generated by Django 5.1.6 on 2025-03-03 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='people_table',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Full_name', models.CharField(max_length=100, verbose_name='Full Name')),
                ('Father_name', models.CharField(max_length=100, verbose_name='Father Name')),
                ('Mother_name', models.CharField(max_length=100, verbose_name='Mother Name')),
                ('address', models.CharField(max_length=100, verbose_name='Address')),
                ('Age', models.IntegerField()),
                ('Blood_group', models.CharField(max_length=100, null=True, verbose_name='Blood Group')),
            ],
        ),
    ]
